name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 1. This is the new step you need for pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # Specify the version you use locally

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm' # This speeds up future builds by caching your modules

      - name: Install Dependencies
        run: pnpm install # Changed from npm install

      - name: Build Project
        run: pnpm build # Changed from npm run build

      - name: Deploy to S3
        run: aws s3 sync dist/spa/ s3://${{ secrets.BUCKET_NAME }} --delete 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'

      - name: Clear CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'